/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/Card.vue')['default']
    NutActionSheet: typeof import('@nutui/nutui-taro')['ActionSheet']
    NutAvatar: typeof import('@nutui/nutui-taro')['Avatar']
    NutBadge: typeof import('@nutui/nutui-taro')['Badge']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutCell: typeof import('@nutui/nutui-taro')['Cell']
    NutCellGroup: typeof import('@nutui/nutui-taro')['CellGroup']
    NutCheckbox: typeof import('@nutui/nutui-taro')['Checkbox']
    NutCol: typeof import('@nutui/nutui-taro')['Col']
    NutDialog: typeof import('@nutui/nutui-taro')['Dialog']
    NutImagePreview: typeof import('@nutui/nutui-taro')['ImagePreview']
    NutPrice: typeof import('@nutui/nutui-taro')['Price']
    NutRow: typeof import('@nutui/nutui-taro')['Row']
    NutSkeleton: typeof import('@nutui/nutui-taro')['Skeleton']
    NutSticky: typeof import('@nutui/nutui-taro')['Sticky']
    NutSwipe: typeof import('@nutui/nutui-taro')['Swipe']
    NutSwipeGroup: typeof import('@nutui/nutui-taro')['SwipeGroup']
    NutSwiper: typeof import('@nutui/nutui-taro')['Swiper']
    NutSwiperItem: typeof import('@nutui/nutui-taro')['SwiperItem']
    NutTag: typeof import('@nutui/nutui-taro')['Tag']
    SimpleLine: typeof import('./src/components/SimpleLine.vue')['default']
  }
}
